version: '3.9'

services:
  main:
    container_name: main
    build:
      context: .

    env_file:
      - .development.env
    volumes:
      - ./app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: npm run start:dev
    depends_on:
      - mysql

    restart: always

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=conectt0.2sEcreT
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=conectt
    restart: always